#!/bin/sh

set -e


ORIGINAL_FILE="/usr/lib/python2.7/xmlrpclib.py"
DIVERT_FILE="$ORIGINAL_FILE.divert"
LLIUREX_FILE="/usr/share/n4d-lliurex-base/diversions/xmlrpclib.py"

case "$1" in
   configure)
	deb-systemd-invoke restart n4d || true

   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0
