#!/bin/sh

set -e


ORIGINAL_FILE="/usr/lib/python2.7/xmlrpclib.py"
DIVERT_FILE="$ORIGINAL_FILE.divert"
LLIUREX_FILE="/usr/share/n4d-lliurex-base/diversions/xmlrpclib.py"

case "$1" in
   configure)
	deb-systemd-invoke restart n4d || true

	 if [ ! -r ${DIVERT_FILE} ] ; then

		dpkg-divert --package ${PACKAGE_NAME} --rename --quiet --add --divert  ${DIVERT_FILE}  ${ORIGINAL_FILE}
                ln -fs ${LLIUREX_FILE}  ${ORIGINAL_FILE}
	fi


   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0
