#!/bin/sh

set -e

# Template for diversions

PACKAGE_NAME="n4d-lliurex-base"
ORIGINAL_FILE="/usr/lib/python2.7/xmlrpclib.py"
DIVERT_FILE="$ORIGINAL_FILE.divert"
LLIUREX_FILE="/usr/share/n4d-lliurex-base/diversions/xmlrpclib.py"


case $1 in
        remove|purge|abort-install|disappear)

                if [ -f ${DIVERT_FILE} ] ; then
			rm -rf $ORIGINAL_FILE || true
                        dpkg-divert --package  ${PACKAGE_NAME} --rename --quiet --remove ${ORIG_FILE}|| true
                fi

                ;;
        *)
                echo "Nothing to do"
                ;;
esac

#DEBHELPER#

exit 0

